### ISSUE TITLE
Typo in line 27 'RIBU_RESIZE_HIGHT' 

### ISSUE THREAD

**Issue by stfnschrmr** [WPsites/Resize-images-before-upload#2]
There is a typo in line 27 which causes an error when defining 'RIBU_RESIZE_HEIGHT' in wp-config.php

**Comment by WPsites** [comment]
Thanks for pointing this out.

I will fix the typo and have the plugin updated on WordPress.org in the next few days.

**Comment by WPsites** [comment]
I've pushed an update to the WordPress.org repository to fix this.
