### ISSUE TITLE
header already send

### ISSUE THREAD

**Issue by ratmz** [WPsites/Resize-images-before-upload#9]
conflict with other plugin, 

Warning: session_start() [function.session-start]: Cannot send session cache limiter - headers already sent (output started at /.../.../.../recent-tweets-widget/widget.php:240)
in /..../..../..../resize-images-before-upload/resize-images-before-upload.php on line 14

Regards,
Dave

**Comment by WPsites** [comment]
Yes looks like there is a problem with the recent-tweets-widget plugin. I will send them a support request to tell them how to fix.
